import '@/ui/globals.css';
import { nunito } from '@/ui/fonts';

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={nunito.variable} lang="en">
      <body>{children}</body>
    </html>
  );
}
