import { Nunito } from 'next/font/google';
import './globals.css';

const font = Nunito({
  subsets: ['vietnamese'],
  variable: '--font-sans',
  weight: 'variable',
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html className={font.variable} lang="en">
      <body>{children}</body>
    </html>
  );
}
