import '@/app/globals.css';
import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import React from 'react';
import { Toaster } from '@codefixlabs/ui';

const nunito = Nunito({
  subsets: ['vietnamese'],
  variable: '--font-sans',
  weight: 'variable',
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): React.JSX.Element {
  return (
    <html className={`${nunito.variable} dark`} lang="en">
      <body className="bg-background text-foreground">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
